services:
  app:
    build: .
    ports:
      - "8501:8501"
      - "8888:8888"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data
      - ./sqlite_db:/app/sqlite_db
      - ./src:/app/src
    env_file:
      - .env